# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files and typescript config
COPY package.json package-lock.json* tsconfig.json ./

# Copy source
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# Runtime image
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy only built files and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Copy package.json for completeness
COPY package.json ./

# Default command
CMD ["node", "dist/index.js"]